# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-13 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0002_itc_its'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
