# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-13 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0004_csr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csr',
            old_name='name',
            new_name='city',
        ),
    ]
