# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0005_auto_20180814_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdc',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
