# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0006_bdc_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
