# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-04 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lgzp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mon_wa', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('work_exp', models.CharField(max_length=20)),
                ('work_lable', models.CharField(max_length=100)),
                ('work_desp', models.CharField(max_length=10000)),
                ('work_area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='qtzp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mon_wa', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('work_exp', models.CharField(max_length=20)),
                ('work_lable', models.CharField(max_length=100)),
                ('work_desp', models.CharField(max_length=10000)),
                ('work_area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='zlzp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mon_wa', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('work_exp', models.CharField(max_length=20)),
                ('work_lable', models.CharField(max_length=100)),
                ('work_desp', models.CharField(max_length=10000)),
                ('work_area', models.CharField(max_length=20)),
                ('leibie', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='testtb',
        ),
    ]
